# Generated by Django 3.0.7 on 2020-09-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='phone',
            new_name='photo',
        ),
    ]
